# Generated by Django 6.0.3 on 2026-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_group',
            field=models.BooleanField(default=True),
        ),
    ]
