# Generated by Django 6.0.3 on 2026-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mode',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('professional', 'Professional')], default='beginner', max_length=20),
        ),
    ]
